name: Introducing Basic Analysis
category: analysis
authors: ""
shortdesc: In this course we will explore some of the issues in simulation preparation and analysis that can trip up the unwary, and how to avoid them.
longdesc: ""
